# 0.0 Data Dictionary

The notbook is to explore the dataset and build a data dictionary for the raw data

## Import necessary packages

In [ ]:
import pandas as pd
import numpy as np
import glob
import os

## Import data to colab

In [ ]:
from google.colab import files
uploaded = files.upload()

## Import dataframe as df

In [ ]:
#Read all file in the folder
file_path = '/content/Raw_Data_Machine_Learning/'
file_list = os.listdir(file_path)


#Combine all files into one files
df_append = pd.DataFrame()
for file in file_list:
  file_df_temp = pd.read_csv(f'{file_path}{file}')
  df_append = df_append.append(file_df_temp, ignore_index=True)

df = df_append 

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (11) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


Unnamed: 0           SHIPMENT ID             CUSTOMER  DISTANCE  \
0                 0     EXEL.B21109E01579  7931282203445289709    598.37   
1                 1     EXEL.B21109E01585  7931282203445289709   1076.40   
2                 2     EXEL.B21109E01587  7931282203445289709   2137.40   
3                 3     EXEL.B21109E01587  7931282203445289709   2137.40   
4                 4     EXEL.B21109E01598  7931282203445289709   2137.40   
...             ...                   ...                  ...       ...   
9593944      106275  MTNORAM.B21293M02565  6730733317742620471     22.10   
9593945      106276  MTNORAM.B21293M02554  6730733317742620471      0.00   
9593946      106277  MTNORAM.B21293M02554  6730733317742620471      0.00   
9593947      106278  MTNORAM.B21293M02554  6730733317742620471      0.00   
9593948      106279  MTNORAM.B21293M02554  6730733317742620471      0.00   

         CASES    WEIGHT      VOLUME   SOURCE LOCATION ID  \
0           38  30460.76  1480202.58 -5168068385082994908   
1            3     28.26       82.48  6677661768721284933   
2          192   4607.96   295650.00 -5168068385082994908   
3          192   4607.96   295650.00 -5168068385082994908   
4           37    477.04    24448.39 -5168068385082994908   
...        ...       ...         ...                  ...   
9593944      1      1.00        1.00  -145578701977014480   
9593945      1      1.00        1.00  4774428971583591354   
9593946      1      1.00        1.00  4774428971583591354   
9593947      1      1.00        1.00  4774428971583591354   
9593948      1      1.00        1.00  4774428971583591354   

                 ORIGIN NAME   ORIGIN CITY  ... FUEL COSTS ACC. COSTS  \
0        2665167955922709351      FAIRBURN  ...     185.49        0.0   
1       -5397954047813929205     WORCESTER  ...      14.01        0.0   
2        2665167955922709351      FAIRBURN  ...     103.94        8.0   
3        2665167955922709351      FAIRBURN  ...     103.94        8.0   
4        2665167955922709351      FAIRBURN  ...      16.69        8.0   
...                      ...           ...  ...        ...        ...   
9593944  4847614557676040377   SHELBYVILLE  ...      11.20        0.0   
9593945 -8441947025641042803  FAYETTEVILLE  ...       8.00        0.0   
9593946 -8441947025641042803  FAYETTEVILLE  ...       8.00        0.0   
9593947 -8441947025641042803  FAYETTEVILLE  ...       8.00        0.0   
9593948 -8441947025641042803  FAYETTEVILLE  ...       8.00        0.0   

         TOTAL ACTUAL COST           PU_APPT           DL_APPT  \
0                  1726.79  2021-04-23 16:04  2021-04-29 03:04   
1                   112.01  2021-04-22 10:04  2021-04-26 14:04   
2                   838.80  2021-04-21 17:04  2021-05-05 06:05   
3                   838.80  2021-04-21 17:04  2021-05-05 06:05   
4                   141.42  2021-04-21 16:04  2021-04-26 20:04   
...                    ...               ...               ...   
9593944             291.20  2021-10-26 13:10  2021-10-26 18:10   
9593945             208.00  2021-10-26 13:10  2021-10-26 14:10   
9593946             208.00  2021-10-26 13:10  2021-10-26 14:10   
9593947             208.00  2021-10-26 13:10  2021-10-26 14:10   
9593948             208.00  2021-10-26 13:10  2021-10-26 14:10   

             PU_ARRIVAL (X3)     PU_DEPARTED (AF)      DL_ARRIVAL (X1)  \
0        04/23/2021 12:00:00  04/28/2021 08:00:00             NO EVENT   
1        04/22/2021 06:11:00  04/22/2021 06:23:00  04/26/2021 10:03:00   
2        04/21/2021 13:11:00  04/21/2021 13:37:00             NO EVENT   
3        04/21/2021 13:11:00  04/21/2021 13:37:00             NO EVENT   
4        04/21/2021 12:59:00  04/21/2021 13:11:00             NO EVENT   
...                      ...                  ...                  ...   
9593944             NO EVENT             NO EVENT             NO EVENT   
9593945             NO EVENT             NO EVENT             NO EVENT   
9593946             NO EVEN

## Show the head of the data

In [ ]:
df.head()

Unnamed: 0        SHIPMENT ID             CUSTOMER  DISTANCE  CASES  \
0           0  EXEL.B21109E01579  7931282203445289709    598.37     38   
1           1  EXEL.B21109E01585  7931282203445289709   1076.40      3   
2           2  EXEL.B21109E01587  7931282203445289709   2137.40    192   
3           3  EXEL.B21109E01587  7931282203445289709   2137.40    192   
4           4  EXEL.B21109E01598  7931282203445289709   2137.40     37   

     WEIGHT      VOLUME   SOURCE LOCATION ID          ORIGIN NAME ORIGIN CITY  \
0  30460.76  1480202.58 -5168068385082994908  2665167955922709351    FAIRBURN   
1     28.26       82.48  6677661768721284933 -5397954047813929205   WORCESTER   
2   4607.96   295650.00 -5168068385082994908  2665167955922709351    FAIRBURN   
3   4607.96   295650.00 -5168068385082994908  2665167955922709351    FAIRBURN   
4    477.04    24448.39 -5168068385082994908  2665167955922709351    FAIRBURN   

   ... FUEL COSTS ACC. COSTS  TOTAL ACTUAL COST           PU_APPT  \
0  ...     185.49        0.0            1726.79  2021-04-23 16:04   
1  ...      14.01        0.0             112.01  2021-04-22 10:04   
2  ...     103.94        8.0             838.80  2021-04-21 17:04   
3  ...     103.94        8.0             838.80  2021-04-21 17:04   
4  ...      16.69        8.0             141.42  2021-04-21 16:04   

            DL_APPT      PU_ARRIVAL (X3)     PU_DEPARTED (AF)  \
0  2021-04-29 03:04  04/23/2021 12:00:00  04/28/2021 08:00:00   
1  2021-04-26 14:04  04/22/2021 06:11:00  04/22/2021 06:23:00   
2  2021-05-05 06:05  04/21/2021 13:11:00  04/21/2021 13:37:00   
3  2021-05-05 06:05  04/21/2021 13:11:00  04/21/2021 13:37:00   
4  2021-04-26 20:04  04/21/2021 12:59:00  04/21/2021 13:11:00   

       DL_ARRIVAL (X1)     DL_DEPARTED (D1)            Insert Date  
0             NO EVENT             NO EVENT  2021-04-19 14:35:04.0  
1  04/26/2021 10:03:00  04/26/2021 10:31:00  2021-04-19 14:36:00.0  
2             NO EVENT             NO EVENT  2021-04-19 14:36:18.0  
3             NO EVENT             NO EVENT  2021-04-19 14:36:18.0  
4             NO EVENT             NO EVENT  2021-04-19 14:38:50.0  

[5 rows x 31 columns]

In [ ]:
# Check the dataframe shape
df.shape

(9593949, 31)

We will have 9593949 avaliable data and 31 attributes.

In [ ]:
# Explor Columnn Name
df.columns

Index(['Unnamed: 0', 'SHIPMENT ID', 'CUSTOMER', 'DISTANCE', 'CASES', 'WEIGHT',
       'VOLUME', 'SOURCE LOCATION ID', 'ORIGIN NAME', 'ORIGIN CITY',
       'ORIGIN STATE', 'ORIGIN ZIP', 'DEST LOCATION ID', 'CONSIGNEE NAME',
       'DEST CITY', 'DEST STATE', 'DEST ZIP', 'ACTUAL CARRIER', 'ACTUAL MODE',
       'ACTUAL EQUIP', 'LINEHAUL COSTS', 'FUEL COSTS', 'ACC. COSTS',
       'TOTAL ACTUAL COST', 'PU_APPT', 'DL_APPT', 'PU_ARRIVAL (X3)',
       'PU_DEPARTED (AF)', 'DL_ARRIVAL (X1)', 'DL_DEPARTED (D1)',
       'Insert Date'],
      dtype='object')

## Use descirbe to check each colomns

In [ ]:
print(df.columns[1])
print(df[df.columns[1]].describe())
df[df.columns[1]].unique()

SHIPMENT ID
count               9593949
unique              6215588
top       EXEL.B20013E05264
freq                    416
Name: SHIPMENT ID, dtype: object


array(['EXEL.B21109E01579', 'EXEL.B21109E01585', 'EXEL.B21109E01587', ...,
       'MTNORAM.B21260M02561', 'MTNORAM.B21293M02565',
       'MTNORAM.B21293M02554'], dtype=object)

In [ ]:
print(df.columns[2])
print(df[df.columns[2]].describe())
df[df.columns[2]].unique()

CUSTOMER
count    9.593949e+06
mean    -2.148832e+17
std      4.901297e+18
min     -9.200370e+18
25%     -3.665155e+18
50%      8.385783e+17
75%      4.191757e+18
max      8.851275e+18
Name: CUSTOMER, dtype: float64


array([ 7931282203445289709, -8358465311509355165, -3665154987542956914,
        3665738925766910068,   867406211532405296,  4191756812580544691,
         838578263169818307, -6247082897620015166,                    0,
        6596951253754028338,  6654920838849166547,  4658975030093546156,
        8392937018381327041,  -813095935719371048, -7452257991572485329,
       -4569629250648826880,  1063779951993601303, -6379206090823315922,
        3853771975598788124, -7931931740654582701,    58007119102610273,
        6147743172216528207, -2995043043207070585,  8242222325749600355,
        3349972983819901886,  -865097432476160443, -1377495357862618522,
         929596776556318203,  4096044733432907692,  -184540631604629769,
       -2486853259962530932, -6406978759533183754, -8489056445563148089,
       -9104467330347197426,  -445387823294337361,  6730733317742620471,
         172293849311328526,  2864899793764999156, -6448224029061623688,
       -2381075221362153849,  5280141912971247748, 

In [ ]:
print(df.columns[3])
print(df[df.columns[3]].describe())
df[df.columns[3]].unique()

DISTANCE
count    9.593948e+06
mean     1.228879e+04
std      4.461865e+06
min      0.000000e+00
25%      6.260000e+01
50%      4.876000e+02
75%      9.955600e+02
max      2.000000e+09
Name: DISTANCE, dtype: float64


array([ 598.37, 1076.4 , 2137.4 , ..., 1826.65,  688.61,  472.87])

In [ ]:
print(df.columns[4])
print(df[df.columns[4]].describe())
df[df.columns[4]].unique()

CASES
count    9.593949e+06
mean     3.060328e+02
std      3.773776e+03
min      0.000000e+00
25%      0.000000e+00
50%      2.000000e+00
75%      1.100000e+01
max      2.471000e+06
Name: CASES, dtype: float64


array([   38,     3,   192, ..., 25944, 76468, 10774])

In [ ]:
print(df.columns[5])
print(df[df.columns[5]].describe())
df[df.columns[5]].unique()

WEIGHT
count    9.593949e+06
mean     3.066586e+03
std      2.890548e+05
min      0.000000e+00
25%      2.230000e+00
50%      1.664000e+01
75%      4.468000e+02
max      8.722421e+08
Name: WEIGHT, dtype: float64


array([3.046076e+04, 2.826000e+01, 4.607960e+03, ..., 4.626450e+03,
       2.798383e+04, 3.723820e+04])

In [ ]:
print(df.columns[6])
print(df[df.columns[6]].describe())
df[df.columns[6]].unique()

VOLUME
count    9.593949e+06
mean     1.397595e+04
std      1.795347e+05
min      0.000000e+00
25%      2.400000e-01
50%      4.658000e+01
75%      7.673600e+02
max      3.015666e+08
Name: VOLUME, dtype: float64


array([1.48020258e+06, 8.24800000e+01, 2.95650000e+05, ...,
       1.25974000e+03, 2.01717000e+03, 8.94160000e+02])

In [ ]:
print(df.columns[7])
print(df[df.columns[7]].describe())
df[df.columns[7]].unique()

SOURCE LOCATION ID
count    9.593949e+06
mean    -1.787564e+18
std      4.819409e+18
min     -9.223225e+18
25%     -4.521407e+18
50%     -3.597012e+18
75%      1.915760e+18
max      9.223259e+18
Name: SOURCE LOCATION ID, dtype: float64


array([-5168068385082994908,  6677661768721284933,  1100389784110909198,
       ...,  1544435160812832214, -7284466898126520758,
        8973657966618111992])

In [ ]:
print(df.columns[8])
print(df[df.columns[8]].describe())
df[df.columns[8]].unique()

ORIGIN NAME
count    9.593949e+06
mean    -7.811926e+17
std      5.717549e+18
min     -9.223044e+18
25%     -6.269595e+18
50%     -2.320357e+18
75%      5.729649e+18
max      9.223152e+18
Name: ORIGIN NAME, dtype: float64


array([ 2665167955922709351, -5397954047813929205, -7952887738830377556,
       ...,   984964789215469440,  3156003568563512079,
       -7908201072115559040])

In [ ]:
print(df.columns[9])
print(df[df.columns[9]].describe())
df[df.columns[9]].unique()

ORIGIN CITY
count     9593891
unique       9555
top       Memphis
freq      1560405
Name: ORIGIN CITY, dtype: object


array(['FAIRBURN', 'WORCESTER', 'OVERLAND', ..., 'WEST MENLO PARK',
       'ROCK  HILL', 'GUAYNABO'], dtype=object)

In [ ]:
print(df.columns[10])
print(df[df.columns[10]].describe())
df[df.columns[10]].unique()

ORIGIN STATE
count     9593623
unique        104
top            TN
freq      2659459
Name: ORIGIN STATE, dtype: object


array(['GA', 'MA', 'MO', 'TX', 'IN', 'MI', 'WA', 'TN', 'CA', 'OH', 'NJ',
       'OK', 'WI', 'PA', 'IL', 'ON', 'OR', 'NC', 'LA', 'AZ', 'NM', 'CT',
       'FL', 'SC', 'DE', 'NY', 'ME', 'KY', 'BC', 'MN', 'MS', 'MD', 'VA',
       'AL', 'NV', 'CO', 'KS', 'NE', 'UT', 'MT', 'IA', 'AR', 'SD', 'ND',
       'WV', 'RI', 'ID', 'VT', 'WY', nan, 'NH', 'HI', 'DC', 'QC', 'CN',
       'JP', 'MX', 'AT', 'GB', 'MY', 'KR', 'FR', 'MH', 'SG', 'AE', 'PQ',
       'CH', 'MB', 'SW', 'TW', 'RO', 'KA', 'LK', 'AB', 'PO', 'NL', 'IT',
       'ES', 'AK', 'TS', 'WN', 'PH', 'EM', 'QT', 'QU', 'GT', 'DF', 'CU',
       'JA', 'CI', 'SL', 'AG', 'TM', 'TL', 'PU', 'SK', 'NB', 'NS', 'NT',
       '**', 'OHIO', 'YT', 'MAINE', 'UTAH', 'PR'], dtype=object)

In [ ]:
print(df.columns[11])
print(df[df.columns[11]].describe())
df[df.columns[11]].unique()

ORIGIN ZIP
count     9593901
unique      30332
top         38134
freq      1476195
Name: ORIGIN ZIP, dtype: object


array(['30213', '01607', '63114-5765', ..., '00965', '11717-1031',
       '68138'], dtype=object)

In [ ]:
print(df.columns[12])
print(df[df.columns[12]].describe())
df[df.columns[12]].unique()

DEST LOCATION ID
count    9.593949e+06
mean    -6.512055e+16
std      5.207173e+18
min     -9.223371e+18
25%     -4.352950e+18
50%     -4.689664e+16
75%      4.295778e+18
max      9.223369e+18
Name: DEST LOCATION ID, dtype: float64


array([ -272273051616801586, -5168068385082994908, -1431067929610151670,
       ..., -7077934204346751229, -8342219633499654059,
        1678028161399067476])

In [ ]:
print(df.columns[13])
print(df[df.columns[13]].describe())
df[df.columns[13]].unique()

CONSIGNEE NAME
count    9.593949e+06
mean    -1.746143e+17
std      5.297765e+18
min     -9.223355e+18
25%     -4.833694e+18
50%     -2.224451e+17
75%      4.537944e+18
max      9.223361e+18
Name: CONSIGNEE NAME, dtype: float64


array([ -882153881375172960,  2665167955922709351,  3875366048091336758,
       ..., -6901547901783801993,  3797939738092868452,
       -4555001953984694022])

In [ ]:
print(df.columns[14])
print(df[df.columns[14]].describe())
df[df.columns[14]].unique()

DEST CITY
count     9593786
unique      21750
top       EVERETT
freq       495905
Name: DEST CITY, dtype: object


array(['BELLEVILLE', 'FAIRBURN', 'MIRA LOMA', ..., 'FRANKFRORD',
       'SNOQUALMIE PASS', 'EASE SYRACUSE'], dtype=object)

In [ ]:
print(df.columns[15])
print(df[df.columns[15]].describe())
df[df.columns[15]].unique()

DEST STATE
count     9591527
unique        160
top            WA
freq      1116200
Name: DEST STATE, dtype: object


array(['MI', 'GA', 'CA', 'WA', 'IL', 'NV', 'NC', 'IN', 'AZ', 'TN', 'MD',
       'FL', 'CT', 'TX', 'NY', 'KS', 'CO', 'MO', 'OH', 'NJ', 'PA', 'ID',
       'IA', 'MS', 'KY', 'MN', 'WV', 'UT', 'RI', 'VA', 'MA', 'AL', 'WI',
       'OK', nan, 'SC', 'OR', 'ME', 'LA', 'WY', 'AR', 'HI', 'AK', 'NE',
       'SD', 'NM', 'VT', 'ND', 'NH', 'MT', 'PR', 'DC', 'DE', 'VI', 'GU',
       'AS', 'ON', 'QC', 'BC', 'NS', 'AB', 'NB', '12', 'SK', 'MB', 'YT',
       'NL', '**', 'JP', 'PQ', 'PE', '01', 'P01', 'AE', 'GB', '99', 'SP',
       'IT', 'C', 'RM', '3', 'NT', 'BO', 'N', 'JA', 'RJ', 'SY', '100',
       'UK', 'IO', '77041', 'AG', 'EM', 'QT', 'QU', 'MR', 'GT', 'CU',
       '47', '11', 'MX', 'TM', 'DB', 'SL', '48', 'MP', 'BE', 'FM', 'Z2',
       'PIN', 'PW', 'SH', 'J5', 'MG', 'RS', 'NSW', '74131', 'MADRID',
       'TX.', 'TEXAS', 'CA \t', '1', 'ZH', '7', 'ER', 'MY', 'KA', 'WZ',
       '73129', 'XX', '??', 'SS', 'KL', 'MH', '28', '75', '00', 'RU',
       '08', 'LO', '13', 'AT', '21', 'BK', 'SE', '10', '45', '0

In [ ]:
print(df.columns[16])
print(df[df.columns[16]].describe())
df[df.columns[16]].unique()

DEST ZIP
count     9593605
unique     201367
top         98204
freq       452555
Name: DEST ZIP, dtype: object


array(['48111', '30213', '91752', ..., 'V3R 0A1', '06095-5709', 'L5J 2Z5'],
      dtype=object)

In [ ]:
print(df.columns[17])
print(df[df.columns[17]].describe())
#df[df.columns[17]].unique()

ACTUAL CARRIER
count    9.593949e+06
mean     1.824553e+18
std      3.983408e+18
min     -9.207727e+18
25%     -1.825974e+17
50%      3.427574e+18
75%      4.527271e+18
max      9.167988e+18
Name: ACTUAL CARRIER, dtype: float64


In [ ]:
print(df.columns[18])
print(df[df.columns[18]].describe())
df[df.columns[18]].unique()

ACTUAL MODE
count         9591740
unique             31
top       CORP.PARCEL
freq          5002781
Name: ACTUAL MODE, dtype: object


array(['CORP.TL', 'CORP.LTL', 'CORP.PARCEL', 'CORP.AIR', 'PARCEL', 'LTL',
       'CORP.INTERMODAL', 'CORP.UNKNOWN', 'CORP.OCEAN-LCL',
       'CORP.AIR-CONSOL', 'CORP.AIR-DIRECT', 'CORP.OCEAN-FCL',
       'EXEL.COURIER', 'MTNORAM.INTERMODAL', 'MTNORAM.TL', 'MTNORAM.LTL',
       'TL', 'MTNORAM.PARCEL', 'CORP.OCEAN', 'PLNA.PARCEL', 'PLNA.LTL',
       'EXEL.LTL', 'CORP.SPECIALIZED', 'MTNORAM.OCEAN', 'RAIL', 'PLNA.TL',
       'CARRIER.LTL', nan, 'CORP.OTHER', 'MTNORAM.RAIL', 'UTCRIQ.TL',
       'AIR'], dtype=object)

In [ ]:
print(df.columns[20])
print(df[df.columns[20]].describe())

LINEHAUL COSTS
count    9.593949e+06
mean     5.800929e+02
std      1.914286e+04
min     -1.933960e+03
25%      4.500000e+00
50%      9.230000e+00
75%      1.500000e+02
max      1.143635e+07
Name: LINEHAUL COSTS, dtype: float64


In [ ]:
print(df.columns[21])
print(df[df.columns[21]].describe())

FUEL COSTS
count    9.593949e+06
mean     2.661117e+01
std      1.145453e+02
min     -1.463530e+03
25%      0.000000e+00
50%      0.000000e+00
75%      6.400000e-01
max      2.886983e+04
Name: FUEL COSTS, dtype: float64


In [ ]:
print(df.columns[22])
print(df[df.columns[22]].describe())

ACC. COSTS
count    9.593949e+06
mean     1.120043e+01
std      2.348755e+02
min     -1.498850e+03
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      1.233950e+05
Name: ACC. COSTS, dtype: float64


In [ ]:
print(df.columns[23])
print(df[df.columns[23]].describe())
df[df.columns[23]].unique()

TOTAL ACTUAL COST
count    9.593949e+06
mean     6.197886e+02
std      1.915064e+04
min     -3.394600e+02
25%      4.730000e+00
50%      9.740000e+00
75%      1.672000e+02
max      1.143682e+07
Name: TOTAL ACTUAL COST, dtype: float64


array([1726.79,  112.01,  838.8 , ..., 2834.38, 2346.09, 2542.16])

In [ ]:
print(df.columns[24])
print(df[df.columns[24]].describe())
df[df.columns[24]].unique()

PU_APPT
count              9593949
unique               56977
top       12/18/2020 22:12
freq                 22650
Name: PU_APPT, dtype: object


array(['2021-04-23 16:04', '2021-04-22 10:04', '2021-04-21 17:04', ...,
       '2021-10-29 05:00', '2021-11-17 15:30', '2021-10-30 05:00'],
      dtype=object)

In [ ]:
print(df.columns[25])
print(df[df.columns[25]].describe())
df[df.columns[25]].unique()

DL_APPT
count             9593949
unique              77545
top       12/11/2020 5:12
freq                12053
Name: DL_APPT, dtype: object


array(['2021-04-29 03:04', '2021-04-26 14:04', '2021-05-05 06:05', ...,
       '2021-10-30 19:00', '2021-11-01 17:30', '2021-10-30 15:00'],
      dtype=object)

In [ ]:
print(df.columns[26])
print(df[df.columns[26]].describe())
df[df.columns[26]].unique()

PU_ARRIVAL (X3)
count      9593949
unique     1365385
top       NO EVENT
freq       4717067
Name: PU_ARRIVAL (X3), dtype: object


array(['04/23/2021 12:00:00', '04/22/2021 06:11:00',
       '04/21/2021 13:11:00', ..., '09/29/2021 08:40:35',
       '09/21/2021 20:40:56', '10/07/2021 13:23:09'], dtype=object)

In [ ]:
print(df.columns[27])
print(df[df.columns[27]].describe())
df[df.columns[27]].unique()

PU_DEPARTED (AF)
count      9593949
unique     1242839
top       NO EVENT
freq       4740147
Name: PU_DEPARTED (AF), dtype: object


array(['04/28/2021 08:00:00', '04/22/2021 06:23:00',
       '04/21/2021 13:37:00', ..., '10/28/2021 04:48:00',
       '10/24/2021 15:31:00', '11/13/2021 09:48:00'], dtype=object)

In [ ]:
print(df.columns[28])
print(df[df.columns[28]].describe())
df[df.columns[28]].unique()

DL_ARRIVAL (X1)
count      9593949
unique      514941
top       NO EVENT
freq       7302818
Name: DL_ARRIVAL (X1), dtype: object


array(['NO EVENT', '04/26/2021 10:03:00', '04/26/2021 11:37:00', ...,
       '10/30/2021 12:24:00', '10/28/2021 20:25:00',
       '10/30/2021 07:30:00'], dtype=object)

In [ ]:
print(df.columns[29])
print(df[df.columns[29]].describe())
df[df.columns[29]].unique()

DL_DEPARTED (D1)
count      9593949
unique     1284292
top       NO EVENT
freq       4250908
Name: DL_DEPARTED (D1), dtype: object


array(['NO EVENT', '04/26/2021 10:31:00', '04/26/2021 11:42:00', ...,
       '11/01/2021 11:21:46', '10/29/2021 00:46:00',
       '10/14/2021 07:51:00'], dtype=object)

In [ ]:
print(df.columns[30])
print(df[df.columns[30]].describe())
df[df.columns[30]].unique()

Insert Date
count     9593949
unique    2831239
top       09:23.0
freq          991
Name: Insert Date, dtype: object


array(['2021-04-19 14:35:04.0', '2021-04-19 14:36:00.0',
       '2021-04-19 14:36:18.0', ..., '2021-09-10 12:06:23.0',
       '2021-09-10 12:00:14.0', '2021-10-20 21:45:29.0'], dtype=object)